baseurl = "https://harishguda.me"
languageCode = "en-us"
title = "Harish Guda"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 4
[[menu.main]]
    name = "CV"
    url = "/files/cv-harishguda.pdf"
    weight = 5

[params]
    description = "Personal Webpage."
    footer = "&copy; [Harish Guda](https://harishguda.me) | [ASU](https://wpcarey.asu.edu/people/profile/3485205) | [Linkedin](https://www.linkedin.com/in/harish-guda/) | [Twitter](https://twitter.com/harish_guda) | [Github](https://github.com/harish-guda) "
